//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLEntityClassGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLEntityClassGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accounts.
        /// </summary>
        public static string AccountsDatabase {
            get {
                return ResourceManager.GetString("AccountsDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEVDB01.
        /// </summary>
        public static string AccountsServerDev {
            get {
                return ResourceManager.GetString("AccountsServerDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m3db01\m3val.
        /// </summary>
        public static string AccountsServerPreProd {
            get {
                return ResourceManager.GetString("AccountsServerPreProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m3db01\m3stage.
        /// </summary>
        public static string AccountsServerQa {
            get {
                return ResourceManager.GetString("AccountsServerQa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All layers for this table have been generated.
        /// </summary>
        public static string AllLayersHaveBeenGenerated {
            get {
                return ResourceManager.GetString("AllLayersHaveBeenGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3.Business.
        /// </summary>
        public static string BusinessNamespace {
            get {
                return ResourceManager.GetString("BusinessNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calm it down, please..
        /// </summary>
        public static string CalmItDownPlease {
            get {
                return ResourceManager.GetString("CalmItDownPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:	5.0.0.8
        ///Author:	jortega
        ///Date:	02/08/2013
        ///Features:
        ///	• None
        ///Fixes:
        ///	• Validate Table Before Generating
        ///	• Fixed Validation Method In Manager
        ///	• Removed OrderSystem Connection String
        ///	• Removed QA and PreProd Level Connection Strings
        ///	• Fixed Custom Properties at Data and Manager Levels
        ///
        ///Version:	5.0.0.7
        ///Author:	jortega
        ///Date:	01/21/2013
        ///Features:
        ///	• Changed Enum Prompt to be Custom Property Prompt
        ///Fixes:
        ///	• Various Validation Method Fixes
        ///
        ///Version:	5.0.0.6
        ///Author:	jortega
        ///Date:	 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently checking view schemas....
        /// </summary>
        public static string CheckingViewSchemas {
            get {
                return ResourceManager.GetString("CheckingViewSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check View Schemas..
        /// </summary>
        public static string CheckViewSchemas {
            get {
                return ResourceManager.GetString("CheckViewSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Created.
        /// </summary>
        public static string ClassCreated {
            get {
                return ResourceManager.GetString("ClassCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLEntityClassGenerator.Templates.ClassTemplate.txt.
        /// </summary>
        public static string ClassTemplate {
            get {
                return ResourceManager.GetString("ClassTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is required for view schema check!.
        /// </summary>
        public static string ConnectionRequiredForViewSchemaCheck {
            get {
                return ResourceManager.GetString("ConnectionRequiredForViewSchemaCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to integrated security=SSPI;persist security info=False;initial catalog={1};data source={0}.
        /// </summary>
        public static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .cs.
        /// </summary>
        public static string CSharpExt {
            get {
                return ResourceManager.GetString("CSharpExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# Files (*.cs)|*.cs|All files (*.*)|*.*.
        /// </summary>
        public static string CSharpFiles {
            get {
                return ResourceManager.GetString("CSharpFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAO Created.
        /// </summary>
        public static string DAOCreated {
            get {
                return ResourceManager.GetString("DAOCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLEntityClassGenerator.Templates.DaoTemplate.txt.
        /// </summary>
        public static string DAOTemplate {
            get {
                return ResourceManager.GetString("DAOTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3.Data.
        /// </summary>
        public static string DataNamespace {
            get {
                return ResourceManager.GetString("DataNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.UFN_GetBeginningOfDTTM(@{0}, &apos;&apos;D&apos;&apos;) AND DATEADD(MINUTE, -1, DATEADD(DAY, 1, dbo.UFN_GetBeginningOfDTTM(@{0}, &apos;&apos;D&apos;&apos;))).
        /// </summary>
        public static string DateComparisonStringFormat {
            get {
                return ResourceManager.GetString("DateComparisonStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLEntityClassGenerator.
        /// </summary>
        public static string DefaultAuthor {
            get {
                return ResourceManager.GetString("DefaultAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go-m3.
        /// </summary>
        public static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3.Entities.
        /// </summary>
        public static string EntitiesNamespace {
            get {
                return ResourceManager.GetString("EntitiesNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3.Entities\Enumerations.cs.
        /// </summary>
        public static string EnumerationsFileLocation {
            get {
                return ResourceManager.GetString("EnumerationsFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard encountered an error copying content..
        /// </summary>
        public static string ErrorCopyingContent {
            get {
                return ResourceManager.GetString("ErrorCopyingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while selection connection string. Using default..
        /// </summary>
        public static string ErrorDeterminingConnectionString {
            get {
                return ResourceManager.GetString("ErrorDeterminingConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorsFound.
        /// </summary>
        public static string ErrorFound {
            get {
                return ResourceManager.GetString("ErrorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while reading embedded resource..
        /// </summary>
        public static string ErrorReadingEmbeddedResource {
            get {
                return ResourceManager.GetString("ErrorReadingEmbeddedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encountered saving file..
        /// </summary>
        public static string ErrorSavingFile {
            get {
                return ResourceManager.GetString("ErrorSavingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	C.*,
        ///	( 
        ///		CASE WHEN EXISTS 
        ///		( 
        ///			SELECT &apos;X&apos;  
        ///			FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC WITH (NoLock)
        ///				JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU WITH (NoLock)
        ///					ON TC.CONSTRAINT_NAME = KCU.CONSTRAINT_NAME AND
        ///					   TC.CONSTRAINT_TYPE = &apos;PRIMARY KEY&apos; AND
        ///					   KCU.COLUMN_NAME = C.COLUMN_NAME AND 
        ///					   TC.TABLE_NAME = C.TABLE_NAME 
        ///		) 
        ///		THEN 1 
        ///		ELSE 0 
        ///		END 
        ///	) as IsPrimaryKey,
        ///	SC.is_identity AS IsIdentity,
        ///	SC.is_computed AS IsComputed
        ///FROM INFORMAT [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetPropertiesQuery {
            get {
                return ResourceManager.GetString("GetPropertiesQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM INFORMATION_SCHEMA.TABLES ORDER BY TABLE_NAME.
        /// </summary>
        public static string GetTablesQuery {
            get {
                return ResourceManager.GetString("GetTablesQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glitch in the Matrix.
        /// </summary>
        public static string GlitchInTheMatrix {
            get {
                return ResourceManager.GetString("GlitchInTheMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSApplication.
        /// </summary>
        public static string GPSApplication {
            get {
                return ResourceManager.GetString("GPSApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has not been implemented yet!.
        /// </summary>
        public static string HasNotBeenImplementedYet {
            get {
                return ResourceManager.GetString("HasNotBeenImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUGE SUCCESS!! EAT CAKE!.
        /// </summary>
        public static string HugeSuccess {
            get {
                return ResourceManager.GetString("HugeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE LIKE &apos;View&apos; AND TABLE_NAME LIKE &apos;{0}&apos;.
        /// </summary>
        public static string IsTableAViewQuery {
            get {
                return ResourceManager.GetString("IsTableAViewQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE &apos;{0}&apos;.
        /// </summary>
        public static string IsTableValid {
            get {
                return ResourceManager.GetString("IsTableValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                     {0} = row.GetValue&lt;{2}&gt;(&quot;{1}&quot;){3},.
        /// </summary>
        public static string LinqString {
            get {
                return ResourceManager.GetString("LinqString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Created.
        /// </summary>
        public static string ManagerCreated {
            get {
                return ResourceManager.GetString("ManagerCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLEntityClassGenerator.Templates.ManagerTemplate.txt.
        /// </summary>
        public static string ManagerTemplate {
            get {
                return ResourceManager.GetString("ManagerTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blahhhh.
        /// </summary>
        public static string MyResource {
            get {
                return ResourceManager.GetString("MyResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1}.
        /// </summary>
        public static string NamespaceString {
            get {
                return ResourceManager.GetString("NamespaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Columns Selected!.
        /// </summary>
        public static string NoColumnsSelected {
            get {
                return ResourceManager.GetString("NoColumnsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Errors on the view schema.
        /// </summary>
        public static string NoErrorsOnViewSchemaCheck {
            get {
                return ResourceManager.GetString("NoErrorsOnViewSchemaCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NonPersistent.
        /// </summary>
        public static string NonPersistent {
            get {
                return ResourceManager.GetString("NonPersistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         /// &lt;param name=&quot;{0}&quot; /&gt;.
        /// </summary>
        public static string ParamDocString {
            get {
                return ResourceManager.GetString("ParamDocString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                         new SqlParameter(&quot;@{0}&quot;, {2}item.{1}),.
        /// </summary>
        public static string ParamString {
            get {
                return ResourceManager.GetString("ParamString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one column..
        /// </summary>
        public static string PleaseSelectAtLeastOneColumn {
            get {
                return ResourceManager.GetString("PleaseSelectAtLeastOneColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                         new SqlParameter(&quot;@{0}&quot;, {2}{1}),.
        /// </summary>
        public static string PrimaryKeyParamString {
            get {
                return ResourceManager.GetString("PrimaryKeyParamString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/// &lt;param name=&quot;{1}&quot;&gt;Primary Key of {2} table&lt;/param&gt;.
        /// </summary>
        public static string PrimaryKeysDocumentation {
            get {
                return ResourceManager.GetString("PrimaryKeysDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        public static string RequiredFieldError {
            get {
                return ResourceManager.GetString("RequiredFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLEntityClassGenerator.Templates.SearchTemplate.txt.
        /// </summary>
        public static string SearchTemplate {
            get {
                return ResourceManager.GetString("SearchTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLEntityClassGenerator.Templates.SPTemplate.txt.
        /// </summary>
        public static string SPTemplate {
            get {
                return ResourceManager.GetString("SPTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Entity Class Generator.
        /// </summary>
        public static string SQLEntityClassGeneratorTitle {
            get {
                return ResourceManager.GetString("SQLEntityClassGeneratorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .sql.
        /// </summary>
        public static string SQLExt {
            get {
                return ResourceManager.GetString("SQLExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Files (*.sql)|*.sql|All files (*.*)|*.*.
        /// </summary>
        public static string SQLFiles {
            get {
                return ResourceManager.GetString("SQLFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Procedures Created.
        /// </summary>
        public static string StoredProceduresCreated {
            get {
                return ResourceManager.GetString("StoredProceduresCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table must be valid..
        /// </summary>
        public static string TableMustBeValid {
            get {
                return ResourceManager.GetString("TableMustBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests Created.
        /// </summary>
        public static string TestsCreated {
            get {
                return ResourceManager.GetString("TestsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3.Tests.
        /// </summary>
        public static string TestsNamespace {
            get {
                return ResourceManager.GetString("TestsNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLEntityClassGenerator.Templates.TestsTemplate.txt.
        /// </summary>
        public static string TestsTemplate {
            get {
                return ResourceManager.GetString("TestsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txt Files (*.txt)|*.txt|All files (*.*)|*.*.
        /// </summary>
        public static string TXTFiles {
            get {
                return ResourceManager.GetString("TXTFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLEntityClassGenerator.Templates.ViewClassTemplate.txt.
        /// </summary>
        public static string ViewClassTemplate {
            get {
                return ResourceManager.GetString("ViewClassTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLEntityClassGenerator.Templates.ViewDaoTemplate.txt.
        /// </summary>
        public static string ViewDAOTemplate {
            get {
                return ResourceManager.GetString("ViewDAOTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLEntityClassGenerator.Templates.ViewManagerTemplate.txt.
        /// </summary>
        public static string ViewManagerTemplate {
            get {
                return ResourceManager.GetString("ViewManagerTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors were found in view schema check. File will be saved..
        /// </summary>
        public static string ViewSchemaCheckErrorsFound {
            get {
                return ResourceManager.GetString("ViewSchemaCheckErrorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 * FROM {0}.
        /// </summary>
        public static string ViewSchemaCheckQuery {
            get {
                return ResourceManager.GetString("ViewSchemaCheckQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE LIKE &apos;View&apos;.
        /// </summary>
        public static string ViewSchemaQuery {
            get {
                return ResourceManager.GetString("ViewSchemaQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLEntityClassGenerator.Templates.ViewSearchTemplate.txt.
        /// </summary>
        public static string ViewSearchTemplate {
            get {
                return ResourceManager.GetString("ViewSearchTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLEntityClassGenerator.Templates.ViewSPTemplate.txt.
        /// </summary>
        public static string ViewSPTemplate {
            get {
                return ResourceManager.GetString("ViewSPTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLEntityClassGenerator.Templates.ViewTestsTemplate.txt.
        /// </summary>
        public static string ViewTestsTemplate {
            get {
                return ResourceManager.GetString("ViewTestsTemplate", resourceCulture);
            }
        }
    }
}
