//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiScript.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiScript.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        internal static string AuditDatabase {
            get {
                return ResourceManager.GetString("AuditDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:	5.0.0.28
        ///Author:	JDuverge
        ///Date:	03/19/2013
        ///Features:
        ///	• Added Default Folders Creation
        ///Fixes:
        ///	• None
        ///
        ///Version:	5.0.0.25
        ///Author:	JDuverge
        ///Date:	02/19/2013
        ///Features:
        ///	• None
        ///Fixes:
        ///	• Fixed Bad Default Folders
        ///
        ///Version:	5.0.0.24
        ///Author:	JDuverge
        ///Date:	02/19/2013
        ///Features:
        ///	• Added New Connection Strings
        ///	• Added Option To Automatically Add Folders
        ///Fixes:
        ///	• None
        ///
        ///Version:	5.0.0.22
        ///Author:	JDuverge
        ///Date:	02/08/2013
        ///Features:
        ///	• Added Connection String To Results
        ///	• Added [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to integrated security=SSPI;persist security info=False;initial catalog={1};data source={0}.
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection String is required!.
        /// </summary>
        internal static string ConnectionStringRequired {
            get {
                return ResourceManager.GetString("ConnectionStringRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder\shell\MultiScript\Command.
        /// </summary>
        internal static string ContextMenuCommand {
            get {
                return ResourceManager.GetString("ContextMenuCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder\shell\MultiScript.
        /// </summary>
        internal static string ContextMenuName {
            get {
                return ResourceManager.GetString("ContextMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courier New.
        /// </summary>
        internal static string CourierNew {
            get {
                return ResourceManager.GetString("CourierNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Connection String: {0}{1}.
        /// </summary>
        internal static string CurrentConnectionString {
            get {
                return ResourceManager.GetString("CurrentConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyyMMdd_HHmmss.
        /// </summary>
        internal static string DateTimeDefaultFormat {
            get {
                return ResourceManager.GetString("DateTimeDefaultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THERE BE DRAGONS AHEAD!.
        /// </summary>
        internal static string DragonsAhead {
            get {
                return ResourceManager.GetString("DragonsAhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An environment must be selected!.
        /// </summary>
        internal static string EnvironmentMustBeSelected {
            get {
                return ResourceManager.GetString("EnvironmentMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting file: {0}{1}.
        /// </summary>
        internal static string ErrorDeletingFile {
            get {
                return ResourceManager.GetString("ErrorDeletingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Deleting Files!.
        /// </summary>
        internal static string ErrorDeletingFiles {
            get {
                return ResourceManager.GetString("ErrorDeletingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR WITH DRAG/DROP!.
        /// </summary>
        internal static string ErrorDragDropTitle {
            get {
                return ResourceManager.GetString("ErrorDragDropTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred Executing Script: {0}{1}.
        /// </summary>
        internal static string ErrorOccurredExecutingScript {
            get {
                return ResourceManager.GetString("ErrorOccurredExecutingScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but there was an error performing the drag and drop function..
        /// </summary>
        internal static string ErrorPerformingDragDrop {
            get {
                return ResourceManager.GetString("ErrorPerformingDragDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors encountered while saving folder/connection:{0}.
        /// </summary>
        internal static string ErrorSavingFolderToRunMessage {
            get {
                return ResourceManager.GetString("ErrorSavingFolderToRunMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Adding Folder!.
        /// </summary>
        internal static string ErrorSavingFolderToRunTitle {
            get {
                return ResourceManager.GetString("ErrorSavingFolderToRunTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Message:{0}.
        /// </summary>
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing Script: {0}{1}.
        /// </summary>
        internal static string ExecutingScript {
            get {
                return ResourceManager.GetString("ExecutingScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-Failures-{0}-{1}.txt.
        /// </summary>
        internal static string FailuresLogFileName {
            get {
                return ResourceManager.GetString("FailuresLogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1.
        /// </summary>
        internal static string FirstArgument {
            get {
                return ResourceManager.GetString("FirstArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Location must be valid!.
        /// </summary>
        internal static string FolderLocationMustBeValid {
            get {
                return ResourceManager.GetString("FolderLocationMustBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Location is required!.
        /// </summary>
        internal static string FolderLocationRequired {
            get {
                return ResourceManager.GetString("FolderLocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs have been saved in the main folder, but we encountered at least one error/warning. Refer to logs for more details..
        /// </summary>
        internal static string LogsSavedWithErrorsOrWarnings {
            get {
                return ResourceManager.GetString("LogsSavedWithErrorsOrWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs have been saved in the main folder. Goodbye..
        /// </summary>
        internal static string LogsSavedWithNoErrors {
            get {
                return ResourceManager.GetString("LogsSavedWithNoErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MultiScript {
            get {
                object obj = ResourceManager.GetObject("MultiScript", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Multi Script.
        /// </summary>
        internal static string MultiScriptTitle {
            get {
                return ResourceManager.GetString("MultiScriptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiScript ran perfectly, so all result logs were removed..
        /// </summary>
        internal static string NoErrorsLogRemoved {
            get {
                return ResourceManager.GetString("NoErrorsLogRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sub folders were found in the selected folder..
        /// </summary>
        internal static string NoSubFoldersFound {
            get {
                return ResourceManager.GetString("NoSubFoldersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to run MultiScript on a Production server?.
        /// </summary>
        internal static string ProductionServerWarning {
            get {
                return ResourceManager.GetString("ProductionServerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all log files in selected directory and its subdirectories?.
        /// </summary>
        internal static string RemoveLogFilesWarning {
            get {
                return ResourceManager.GetString("RemoveLogFilesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Log Files.
        /// </summary>
        internal static string RemovingLogFiles {
            get {
                return ResourceManager.GetString("RemovingLogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-ResultsLog-{0}-{1}.txt.
        /// </summary>
        internal static string ResultsLogFileName {
            get {
                return ResourceManager.GetString("ResultsLogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run MultiScript On Selected Folders.
        /// </summary>
        internal static string RunMultiScriptOnSelectedFolders {
            get {
                return ResourceManager.GetString("RunMultiScriptOnSelectedFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running MultiScript On Selected Folders....
        /// </summary>
        internal static string RunningMultiScriptOnSelectedFolders {
            get {
                return ResourceManager.GetString("RunningMultiScriptOnSelectedFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Scripts.
        /// </summary>
        internal static string RunningScripts {
            get {
                return ResourceManager.GetString("RunningScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to run scripts?.
        /// </summary>
        internal static string RunScriptsWarning {
            get {
                return ResourceManager.GetString("RunScriptsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save the results?.
        /// </summary>
        internal static string SaveDialogMessage {
            get {
                return ResourceManager.GetString("SaveDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveDialogTitle {
            get {
                return ResourceManager.GetString("SaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a backup connection string, in case connection string cannot be determined..
        /// </summary>
        internal static string SelectBackupConnection {
            get {
                return ResourceManager.GetString("SelectBackupConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.sql.
        /// </summary>
        internal static string SQLFileExtension {
            get {
                return ResourceManager.GetString("SQLFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: The Stored Procedure {0} Has Been Changed Multiple Times..
        /// </summary>
        internal static string StoredProcChangedMultipleTimes {
            get {
                return ResourceManager.GetString("StoredProcChangedMultipleTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS!.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.txt.
        /// </summary>
        internal static string TextExtension {
            get {
                return ResourceManager.GetString("TextExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-Warnings-{0}-{1}.txt.
        /// </summary>
        internal static string WarningsLogFileName {
            get {
                return ResourceManager.GetString("WarningsLogFileName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 4-NewArticles-{0}-{1}.txt.
        /// </summary>
        internal static string NewArticlesLogFileName
        {
            get
            {
                return ResourceManager.GetString("NewArticlesLogFileName", resourceCulture);
            }
        }
    }
}
